### ISSUE TITLE
一些小改进

### ISSUE THREAD

**Issue by yyx990803** [BirdEggegg/generator-vue#1]
1. `webpack.production.js` 里面可以加上这个：http://vuejs.org/guide/application.html#Webpack
2. https://github.com/BirdEggegg/generator-vue/blob/master/generators/app/templates/_main.js#L6 这里可以用 `Vue.config.debug = process.env.NODE_ENV !== 'production'`

**Comment by birdgg** [comment]
已修改，感谢
