### ISSUE TITLE
Failed to parse json

### ISSUE THREAD

**Issue by luankefei** [BirdEggegg/generator-vue#4]
➜  www  sudo npm install -g generator-vuejs
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-vuejs"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! file /Users/sunken/www/generator-vuejs/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in array at 27:3
npm ERR!   ],
npm ERR!   ^
npm ERR! File: /Users/sunken/www/generator-vuejs/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sunken/www/npm-debug.log

**Comment by birdgg** [comment]
try `npm cache clean` and install again.

**Comment by luankefei** [comment]
Thank you. it works!
